name: Plugin Check

on:
  push:
    paths:
      - '**.php'
      - '**.js'
      - '**.json'
  pull_request:
    paths:
      - '**.php'
      - '**.js'
      - '**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PHP syntax
        run: find . -name '*.php' -exec php -l {} \;
